language: php

services:
 - rabbitmq

php:
  - 5.3
  - 5.4

before_script:
  - ./scripts/install_librabbitmq-c.sh
  - phpize . && ./configure

script: make test NO_INTERACTION=1 REPORT_EXIT_STATUS=1

